export const englishText = {
  random: [
    `Jelly sweet roll jelly beans biscuit pie macaroon chocolate donut. Carrot cake caramels pie sweet apple pie tiramisu carrot cake. Marzipan marshmallow croissant tootsie roll lollipop. Cupcake lemon drops bear claw gummies. Jelly bear claw gummi bears lollipop cotton candy gummi bears chocolate bar cake cookie. Cupcake muffin danish muffin cookie gummies. Jelly beans tiramisu pudding. Toffee soufflé chocolate cake pastry brownie. Oat cake halvah sweet roll cotton candy croissant lollipop. Macaroon tiramisu chocolate bar candy candy carrot cake jelly sweet. Gummies croissant macaroon dessert. Chocolate cake dragée pie.`,
    `Next level tbh everyday carry, blog copper mug forage kitsch roof party pickled hammock kale chips tofu. Etsy shoreditch 8-bit microdosing, XOXO viral butcher banh mi humblebrag listicle woke bicycle rights brunch before they sold out ramps. Twee shabby chic taiyaki flannel, enamel pin venmo vape four loko. Hexagon kale chips typewriter kitsch 8-bit organic plaid small batch keffiyeh ethical banh mi narwhal echo park cronut.`,
    `Zombie ipsum reversus ab viral inferno, nam rick grimes malum cerebro. De carne lumbering animata corpora quaeritis. Summus brains sit​​, morbo vel maleficia? De apocalypsi gorger omero undead survivor dictum mauris. Hi mindless mortuis soulless creaturas, imo evil stalking monstra adventus resi dentevil vultus comedat cerebella viventium. Qui animated corpse, cricket bat max brucks terribilem incessu zomby. The voodoo sacerdos flesh eater, suscitat mortuos comedere carnem virus. Zonbi tattered for solum oculi eorum defunctis go lum cerebro. Nescio brains an Undead zombies. Sicut malus putrid voodoo horror. Nigh tofth eliv ingdead.`,
    `Cat gets stuck in tree firefighters try to get cat down firefighters get stuck in tree cat eats firefighters' slippers kitty power ignore the squirrels, you'll never catch them anyway for what a cat-ass-trophy! or purr as loud as possible, be the most annoying cat that you can, and, knock everything off the table. Pretend you want to go out but then don't bite off human's toes, yet disappear for four days and return home with an expensive injury; bite the vet so catch eat throw up catch eat throw up bad birds.`,
    `This opera's as lousy as it is brilliant! Your lyrics lack subtlety. You can't just have your characters announce how they feel. That makes me feel angry! Anyhoo, your net-suits will allow you to experience Fry's worm infested bowels as if you were actually wriggling through them.
I just told you! You've killed me! Fry! Quit doing the right thing, you jerk! Michelle, I don't regret this, but I both rue and lament it. Morbo can't understand his teleprompter because he forgot how you say that letter that's shaped like a man wearing a hat.`,
    `Airedale hard cheese mozzarella. Pecorino melted cheese port-salut emmental babybel cheese and wine melted cheese manchego. Everyone loves blue castello everyone loves fromage cheese slices airedale cheddar cream cheese. Bavarian bergkase who moved my cheese halloumi port-salut gouda jarlsberg ricotta rubber cheese. Stinking bishop smelly cheese brie.`,
    `Salvia glossier subway tile, leggings mustache YOLO semiotics chia. Pitchfork tbh af blog church-key meggings vaporware PBR&B master cleanse post-ironic man bun pabst mustache letterpress synth. Snackwave raw denim godard, 3 wolf moon shaman offal kitsch unicorn live-edge selvage schlitz fashion axe vaporware drinking vinegar prism. Shabby chic tacos artisan, chambray chicharrones cardigan leggings typewriter af pop-up williamsburg meditation PBR&B viral. You probably haven't heard of them DIY jean shorts subway tile fashion axe bushwick kitsch tumeric cloud bread vaporware freegan franzen pork belly chicharrones banh mi.`,
    `Man braid celiac synth freegan readymade, pitchfork fam salvia waistcoat lomo bitters gentrify four loko. Pitchfork semiotics post-ironic vegan. Tofu meditation microdosing hashtag semiotics venmo. Flexitarian vape tilde taiyaki. Prism poutine farm-to-table, messenger bag vegan taxidermy tattooed sartorial squid jean shorts fixie selvage trust fund vape.`,
    `Rutters Plate Fleet boom chandler Brethren of the Coast handsomely lookout marooned brigantine knave. Buccaneer gangway jack rum loot spyglass line Jack Tar fore gaff. Gaff topmast scuttle ballast swab draught measured fer yer chains dance the hempen jig Chain Shot yardarm.`,
  ],
  scientific: [
    `The solar system is a collection of celestial bodies that revolve around the Sun, which is at the center of the system. The solar system consists of eight major planets: Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, and Neptune. In addition, there are numerous asteroids, comets, and smaller celestial bodies that orbit the Sun. The Sun, a star located at the heart of the solar system, is the largest object in the system, accounting for about 99.86% of its total mass. The Sun's life began in a molecular cloud, and it continuously spins on its axis. Planets revolve around the Sun in elliptical orbits due to the gravitational pull from the Sun. Terrestrial planets like Earth, Mars, and Venus have solid surfaces, while gas giants like Jupiter and Saturn are predominantly composed of thick gaseous atmospheres. Additionally, there are dwarf planets like Pluto, which lie outside the primary planets. The vast space between planets is filled with many small objects, such as moons, which orbit the planets. The solar system also contains other stars, like binary stars and star clusters, that are millions of light-years away from Earth.`,
    `Stars are the fundamental building blocks of the universe. These massive balls of gas, mostly composed of hydrogen and helium, undergo nuclear fusion in their cores, generating light and heat. The process of fusion powers the stars, and it is what makes them shine brightly. Some stars are relatively small and cool, while others are incredibly large and hot, emitting immense amounts of energy. Over time, stars go through a life cycle, beginning as nebulae (clouds of gas and dust), condensing into protostars, and eventually entering the main sequence phase, where they spend the majority of their existence. As stars age, they can expand into red giants, eventually shedding their outer layers and leaving behind a dense core known as a white dwarf. More massive stars may explode in a supernova, resulting in the creation of neutron stars or black holes. Stars play an essential role in the formation of elements, as they forge heavier elements in their cores through nuclear reactions.`,
    `The concept of time and space is an essential part of understanding the universe. Time is the measure of change, the ongoing sequence of events that occur, while space refers to the vast, seemingly infinite expanse that contains everything in the universe. Albert Einstein's theory of relativity revolutionized our understanding of these concepts by showing that time and space are interconnected, forming what is known as space-time. According to relativity, gravity is not just a force, but a curvature of space-time caused by massive objects. This means that massive objects like planets and stars can warp the space-time around them, affecting the motion of other objects. Space-time also plays a role in the phenomena of time dilation, where time appears to move slower the closer one is to a massive object, such as a planet or a black hole.`,
    `The Milky Way galaxy is a large spiral galaxy that contains our solar system. It is composed of billions of stars, planetary systems, nebulae, and various forms of cosmic matter. The Milky Way spans over 100,000 light-years in diameter, and its center is thought to host a supermassive black hole. The galaxy is part of a local group of galaxies, including the Andromeda Galaxy, the Triangulum Galaxy, and other smaller galaxies. These galaxies are bound together by gravity and are gradually moving toward each other. It is believed that the Milky Way will eventually collide with the Andromeda Galaxy in a few billion years, forming a new galaxy. The study of galaxies provides insights into the formation and evolution of the universe, as well as the behavior of matter and energy on the largest scales.`,
  ],
  motivational: [
    `Life is not just a series of fleeting moments; it is a journey full of challenges that shape us and build our inner strength. Never think of difficulties as obstacles, but as opportunities for personal growth. Sometimes, you may feel that the road ahead is dark, but remember that it is in the darkness where stars shine the brightest. Never listen to those who say you cannot achieve something because only you know your true potential. If you have a dream, don’t wait for the perfect moment to start; create the opportunity yourself. Success does not come easily, but it comes first to those who trust themselves and work tirelessly to reach their goals. If you face failure, remember that it is not the end, but a new beginning towards success. Don’t let any challenge deter you from what you want to achieve, as perseverance is the key to overcoming any obstacle. Think of each step you take as a step toward becoming better, and never let anything stop you from striving to reach your goals. And when you look back in the future, you will be proud of what you have achieved because you never gave up on your dreams.`,
    `The road to success is never easy, but it is always worth it. Every challenge you face is an opportunity to grow stronger and more resilient. The most successful people are not the ones who have faced the least adversity, but the ones who have learned to rise above it. When you encounter difficulties, don’t be discouraged; see them as stepping stones on the path to your goals. Remember that progress is often slow, but as long as you keep moving forward, you are on the right track. Never underestimate the power of persistence. Even small efforts, when done consistently, can lead to great achievements. Believe in yourself and your ability to overcome any obstacle. Your potential is limitless if you keep pushing forward. So take every setback as a lesson and every victory as a reason to keep going. The best is yet to come, so stay focused and keep moving toward your dreams.`,
    `There will be times in your life when you feel overwhelmed by the challenges in front of you. But in those moments, remember that you are stronger than you think. Life tests us not to break us, but to build us. Each trial is a lesson in resilience, and with every obstacle you overcome, you become better prepared for the next one. Don’t let fear or doubt control your actions. Trust in your abilities, because you have everything within you to succeed. It’s not the size of the challenge that matters, but your attitude toward it. Stay positive, stay focused, and never lose sight of your goals. If you fall, get up again. If you face rejection, use it as motivation to push harder. Keep your head high and your heart strong, for success belongs to those who keep moving forward, no matter the odds.`,
    `The key to achieving your dreams is believing in yourself and taking consistent action. There will be moments when it feels like the world is against you, but don’t let those moments define you. You are not defined by your failures, but by how you rise after them. Success is not a destination; it is a journey. The most important thing is not to stop, no matter how difficult the journey may seem. Keep pushing forward, keep learning, and keep growing. Every setback is simply a lesson in disguise, teaching you how to become better. You have the power to change your circumstances, to improve your skills, and to create the life you desire. Don’t wait for the perfect moment to start; start now. Take one step at a time and trust the process. You are capable of more than you realize.`,
    `Never forget that your journey is unique to you. While others may walk different paths, you are on your own journey of self-discovery and growth. The obstacles you face are part of the story that will make you stronger. No one else can walk your path for you, and no one else can define your success. Only you have the power to create the life you want. Keep pushing forward, even when the path is unclear. Your persistence will pay off, and one day, you’ll look back and realize how far you’ve come. The most important thing is to keep believing in yourself and your dreams. Take risks, embrace challenges, and never give up on what you truly desire. The road may be long, but the reward is worth it. So go after your dreams with everything you’ve got, and never stop until you reach them.`,
  ],
};

export const arabicText = {
  random: [
    `حلوى الجيلي، رول الحلوى، فاصوليا الجيلي، بسكويت، فطيرة، ماكارون، شوكولاتة، دونات. كعكة الجزر، كراميل، فطيرة، فطيرة التفاح الحلوة، تيراميسو، كعكة الجزر. مارزيبان، مارسملو، كرواسون، توتسي رول، مصاصة. كب كيك، حلوى الليمون، مخلب الدب، حلوى الجيلي. جيلي، مخلب الدب، حلوى الجيلي، مصاصة، حلوى القطن، حلوى الجيلي، شوكولاتة، كعكة، بسكويت. كب كيك، مافن، دنش، مافن، بسكويت، حلوى الجيلي. فاصوليا الجيلي، تيراميسو، بودينغ. توفي، سوفليه، كعكة الشوكولاتة، معجنات، براوني. كعكة الشوفان، حلاوة، حلوى القطن، كرواسون، مصاصة. ماكارون، تيراميسو، شوكولاتة، حلوى، كعكة الجزر، حلوى الجيلي. حلوى الجيلي، كرواسون، ماكارون، حلوى. كعكة الشوكولاتة، دراجي، فطيرة.`,
    `المرحلة التالية حقيبة حمل يومية، مدونة، كوب نحاسي، تجهيزات، كيتش، حفلة على السطح، مخلل، هاموك، رقائق الكالي، توفو. إيتسي، شورديتش 8-بت، ميكردوزينغ، XOXO، فيرال، جزار، بان مي، هامبلبراغ، لستيكول، ووك، حقوق الدراجة، برانش قبل أن يتم بيعهم، رامب. توي شابي شيك تاياكي، فلانيل، دبوس إناميل، فينمو، فيب، فور لوكو. هيكساگون، رقائق الكالي، آلة كاتبة، كيتش، 8-بت، عضوي، قماش، صغير، كوفيه، أخلاقي، بان مي، ناروال، إيكو بارك، كرونت.`,
    `زومبي إيبسوم، ريفيرسوس، انفجار فيرال، نام ريك غرايمز، مالوم سيريبرو. دي كارني، متحركة، أجسام ميتة، باحثين. سموس براينز سيت​​، موربو، فيل ماليفيكيا؟ دي أبوكاليبس، جورجر، أوميرو، أوندد، سورفايفور، ديكتوم، موريس. هاي ميندليس، مورتيوس، سوليس، كرياتوراس، إيمو، إيفل، ستوكنغ، مونسترا، أدفينتوس، ريسي، دينتيفيل، فولتوس، كوميتي، سيريبيللا، فيفينتيوم. كوي، أنيميتد كورب، كريكت بات، ماكس بروكس، تيرابيليم، إنسيستو، زومبي. ذي فودو، ساكردوس، فليش إيتير، سوسيتيت، مورتيوس، كوميديري، كارنام، فايروس. زومبي تاترد، فور، سولوم، أوكولي، إيوروم، ديفنكتيس، غو لوم، سيريبرو. نيسكو، براينز، أونديد، زومبيز. سيكوت، مالوس، بوتريد، فودو، هورور. نايتوف، إلف، إنغيديد.`,
    `القط عالق في الشجرة، رجال الإطفاء يحاولون إنزال القط، رجال الإطفاء عالقون في الشجرة، القط يأكل شباشب رجال الإطفاء، قوة القط تجاهل السناجب، لن تتمكن من الإمساك بها على أي حال، من أجل ما يُسمى جائزة القط-الأس، أو خرخرة بصوت عالٍ قدر المستطاع، كن أكثر قط مزعج يمكن أن تكونه، واهدم كل شيء على الطاولة. تظاهر بأنك تريد الخروج ولكن لا تفعل ذلك، اعض أصابع الإنسان، ثم اختفِ لمدة أربعة أيام وعد إلى المنزل مع إصابة باهظة الثمن؛ عض الطبيب البيطرى لذا امسك، كل، تقيأ، امسك، كل، تقيأ، طيور سيئة.`,
  ],
  scientific: [
    `النظام الشمسي هو مجموعة من الأجرام السماوية التي تدور حول الشمس، التي تقع في مركز النظام. يتكون النظام الشمسي من ثمانية كواكب رئيسية: عطارد، الزهرة، الأرض، المريخ، المشتري، زحل، أورانوس، ونبتون. بالإضافة إلى ذلك، هناك العديد من الكويكبات والمذنبات والأجرام السماوية الأصغر التي تدور حول الشمس. الشمس، وهي نجم يقع في قلب النظام الشمسي، هي أكبر جسم في النظام، حيث تمثل حوالي 99.86٪ من إجمالي كتلته. بدأت حياة الشمس في سحابة جزيئية، وهي تدور باستمرار على محورها. تدور الكواكب حول الشمس في مدارات إهليلجية بسبب قوة الجاذبية التي تمارسها الشمس. الكواكب الأرضية مثل الأرض، المريخ، والزهرة لها أسطح صلبة، بينما الكواكب الغازية مثل المشتري وزحل تتكون في الغالب من أجواء غازية كثيفة. بالإضافة إلى ذلك، هناك كواكب قزمة مثل بلوتو، التي تقع خارج الكواكب الرئيسية. الفضاء الشاسع بين الكواكب مليء بالعديد من الأجرام السماوية الصغيرة، مثل الأقمار، التي تدور حول الكواكب. يحتوي النظام الشمسي أيضًا على نجوم أخرى، مثل النجوم الثنائية والعناقيد النجمية، التي تبعد ملايين السنين الضوئية عن الأرض.`,
    `النجوم هي اللبنات الأساسية للكون. هذه الكرات العملاقة من الغاز، التي تتكون في الغالب من الهيدروجين والهيليوم، تخضع للاندماج النووي في نواتها، مما يولد الضوء والحرارة. عملية الاندماج هي التي تدفع النجوم، وهي السبب في سطوعها بشكل لامع. بعض النجوم صغيرة وباردة نسبيًا، بينما البعض الآخر ضخم وحار جدًا، مما ينبعث منها كميات هائلة من الطاقة. مع مرور الوقت، تمر النجوم بدورة حياة، حيث تبدأ كسحب غازية (سحب من الغاز والغبار)، ثم تتكاثف إلى نجوم أولية، وأخيرًا تدخل مرحلة التسلسل الرئيسي، حيث تقضي معظم وقتها. مع تقدم النجوم في العمر، يمكن أن تتوسع إلى عمالقة حمراء، وفي النهاية تفرغ طبقاتها الخارجية وتترك وراءها نواة كثيفة تعرف بالقزم الأبيض. النجوم الأكثر ضخامة قد تنفجر في سوبر نوفا، مما يؤدي إلى تكوين نجوم نيترونية أو ثقوب سوداء. تلعب النجوم دورًا أساسيًا في تكوين العناصر، حيث تصنع العناصر الأثقل في نواتها عبر التفاعلات النووية.`,
    `مفهوم الزمن والفضاء هو جزء أساسي من فهم الكون. الزمن هو مقياس التغير، التسلسل المستمر للأحداث التي تحدث، في حين أن الفضاء يشير إلى الامتداد الواسع، الذي يبدو غير محدود، الذي يحتوي على كل شيء في الكون. نظرية النسبية لألبرت أينشتاين أحدثت ثورة في فهمنا لهذه المفاهيم من خلال إظهار أن الزمن والفضاء مترابطان، مما يشكل ما يعرف بالزمن-الفضاء. وفقًا للنسبية، الجاذبية ليست مجرد قوة، ولكنها انحناء في الزمن-الفضاء ناتج عن الأجرام السماوية الضخمة. هذا يعني أن الأجرام السماوية الضخمة مثل الكواكب والنجوم يمكنها تشويه الزمن-الفضاء من حولها، مما يؤثر على حركة الأجرام السماوية الأخرى. يلعب الزمن-الفضاء أيضًا دورًا في ظاهرة تمدد الزمن، حيث يظهر أن الزمن يسير بشكل أبطأ كلما اقتربت من جرم سماوي ضخم، مثل كوكب أو ثقب أسود.`,
    `مجرة درب التبانة هي مجرة حلزونية كبيرة تحتوي على نظامنا الشمسي. تتكون من مليارات النجوم، والأنظمة الكوكبية، والسحب الجزيئية، وأشكال مختلفة من المادة الكونية. تمتد مجرة درب التبانة لأكثر من 100,000 سنة ضوئية في القطر، ويعتقد أن مركزها يحتوي على ثقب أسود ضخم. المجرة هي جزء من مجموعة محلية من المجرات، بما في ذلك مجرة أندروميدا، ومجرة مثلث، ومجرات أخرى أصغر. هذه المجرات مرتبطة ببعضها البعض بالجاذبية وتتحرك تدريجيًا نحو بعضها البعض. يُعتقد أن مجرة درب التبانة ستصطدم في النهاية بمجرة أندروميدا بعد عدة مليارات من السنين، مما يؤدي إلى تشكيل مجرة جديدة. توفر دراسة المجرات رؤى حول تكوين وتطور الكون، بالإضافة إلى سلوك المادة والطاقة على أكبر المقاييس.`,
  ],
  motivational: [
    `إن الحياة ليست مجرد سلسلة من اللحظات العابرة، بل هي رحلة مليئة بالتحديات التي تصقلنا وتزيد من قوتنا الداخلية. لا تظن أبدًا أن الصعاب هي عوائق، بل هي فرص لنموك الشخصي. قد تشعر أحيانًا أن الطريق أمامك مظلم، ولكن تذكر أن الظلام هو ما يجعل النجوم تلمع. لا تلتفت إلى من يقول لك إنه لا يمكنك تحقيق شيء، لأنك وحدك من يعرف قدراتك الحقيقية. إذا كان لديك حلم، فلا تنتظر الفرصة المثالية لتبدأ، بل اصنع الفرصة بنفسك. النجاح لا يأتي بسهولة، ولكنه يأتي أولًا للذين يثقون بأنفسهم ويعملون جاهدين للوصول إلى هدفهم. وإذا كنت تعاني من الفشل، تذكر أنه ليس النهاية، بل بداية جديدة نحو النجاح. لا تدع أي تحدٍ يثنيك عن ما ترغب في تحقيقه، فالمثابرة هي مفتاح التفوق. فكر في كل خطوة تخطوها على أنها خطوة نحو الأفضل، ولا تدع شيء يوقفك عن السعي لتحقيق أهدافك. وعندما تنظر إلى الوراء في المستقبل، ستكون فخورًا بما حققته لأنك لم تتوقف أبدًا عن السعي.`,
    `الحياة ليست مجرد سلسلة من اللحظات العابرة؛ إنها رحلة مليئة بالتحديات التي تشكلنا وتبني قوتنا الداخلية. لا تفكر أبدًا في الصعوبات كعقبات، بل كفرص للنمو الشخصي. في بعض الأحيان، قد تشعر أن الطريق أمامك مظلم، ولكن تذكر أن في الظلام تتألق النجوم بأكثر إشراقًا. كما يقولون، العاصفة لا تدوم، وهي تأتي لتجعلنا أقوى وأكثر مرونة. كل صعوبة تمر بها هي خطوة نحو تحقيق النجاح. الحياة ليست عن الانتظار حتى تهدأ العاصفة، بل عن تعلم الرقص في المطر. عندما تشعر بالإحباط، تذكر أن كل نضالك هو جزء من قصة نجاحك المستقبلي. في النهاية، الجهد الذي تبذله اليوم سيجلب لك ثماره غدًا. لا تدع الخوف من الفشل يوقفك، بل اعتبره درسًا سيساعدك على النجاح في المستقبل.`,
    `لا شيء يأتي بسهولة في الحياة، ولكن القوة الحقيقية تكمن في القدرة على الاستمرار رغم التحديات. كل خطوة صغيرة نحو هدفك هي خطوة مهمة، حتى لو كانت بطيئة. النجاح ليس محض صدفة، بل هو نتيجة العمل الجاد والإصرار. عندما تواجه صعوبة أو فشلًا، تذكر أن النجاح لا يأتي إلا بعد الكثير من الجهد. لا تحبط نفسك لأنك لم تصل بعد إلى الهدف، بل استمتع بالرحلة واكتسب الخبرات التي تجعل منك شخصًا أفضل. لا تستمع إلى من يقولون أنك لن تنجح، لأنهم لا يعرفون قوتك الحقيقية. أنت قادر على تحقيق أي شيء طالما أنك تؤمن بنفسك وتستمر في السعي. كل يوم هو فرصة جديدة لتحقيق أهدافك، فلا تضيعها.`,
    `في الحياة، قد تواجه الكثير من التحديات التي قد تجعلك تشك في قدراتك، لكن تذكر أن العظمة لا تأتي بدون صعوبات. النجاحات الكبيرة تأتي بعد مواجهات حقيقية مع الفشل والصعوبات. في كل مرة تجد نفسك في مأزق، تذكر أن لديك القدرة على التغلب عليه. القوة لا تأتي من الراحة، بل من العمل الجاد والصبر. الأشخاص الناجحون ليسوا أولئك الذين لم يواجهوا التحديات، بل أولئك الذين استمروا في المحاولة رغم تلك التحديات. اليوم هو بداية جديدة، فرصة جديدة لتكون أفضل نسخة من نفسك. لا تقارن رحلتك برحلة الآخرين، فكل شخص له وقته الخاص وطريقه الخاص نحو النجاح. أنت على الطريق الصحيح، فقط استمر في السعي بحماس.`,
    `الشجاعة ليست غياب الخوف، بل القدرة على المضي قدمًا رغم هذا الخوف. في كل مرة تشعر أن الطريق صعب، تذكر أن التحدي هو الذي يصنع منك شخصًا أقوى. الحياة ليست دائمًا مثالية، ولكنها مليئة بالفرص التي تنتظر منك أن تكتشفها. عندما تشعر بالإرهاق، استرح للحظة، ثم استعد للانطلاق مرة أخرى. كل عقبة تقابلك هي فرصة لتعلم شيء جديد عن نفسك وقدراتك. لا تتوقف عن السعي وراء أحلامك لمجرد أنها قد تبدو بعيدة، فالرحلة تستحق العناء. النجاح ليس هدفًا بعيدًا، بل هو عملية مستمرة من النمو والتحسين. استمتع بكل لحظة في رحلتك، حتى تلك التي تبدو مليئة بالصعوبات.`,
    `التغيير هو الجزء الوحيد الثابت في الحياة. إذا كنت ترغب في التقدم، عليك أن تتعلم كيفية التكيف مع التغييرات والتحديات التي تواجهها. النجاح ليس عن الوصول إلى القمة، بل عن الاستمرار في الصعود رغم الصعوبات. لا تخف من الفشل، بل اعتبره درسًا قيمًا يقربك من هدفك. في كل مرة تواجه فيها صعوبة، تذكر أن لديك القوة لتجاوزها. الإصرار هو مفتاح النجاح؛ لا تدع شيئًا يوقفك عن تحقيق أحلامك. الحياة تقدم لك الكثير من الفرص، ولكن يجب أن تكون مستعدًا للاستفادة منها. لا تترك الخوف يوقفك، بل استخدمه كمحفز للمضي قدمًا. النجاح ليس محض مصادفة، بل هو نتيجة للإصرار والعمل الجاد.`,
  ],
};
